# Chocolate Orange Fruit Cake

## Ingredients

### Cake

* 2.5 cups pecans
* 1 cup figs
* 1 cup prunes
* 1 cup dates
* 0.5 cup orange juice
* 2 Tbl grated orange peel
* 0.5 cup orange liquor
* 3 cups flour
* 0.75 cups cocoa
* 2.5 tsp cinnamon
* 1.5 tsp baking powder
* 1.5 tsp baking soda
* 1 lb dark brown sugar
* 6 oz bitter-sweet chocolate
* 0.5 cup butter
* 4 oz cream cheese
* 4 eggs
* 0.75 cups prune butter

### Glaze

* 0.5 cup + 2 Tbl butter
* 1 lb bitter-sweet chocolate
* 6 Tbl orange juice

## Instructions

### Cake

Butter and flour a 12-cupangle food cake pan.

Combine the nuts, fruit, juice, peel, and liquor and let sit for about 30 minutes. 

Sift together all the dry ingredients and chop the chocolate.

Beat the butter, cream cheese, chocolate together. then add the eggs and prune butter and beat some more. Add the dry ingredients and th efruit in thirds, mixing by hand. Pour into the pan and bake until done, about 1 hr at 55 minutes at 325&deg;F. Cool. Wrap in plastic and store about 2 days.

### Glaze

Melt the butter and chocolate. Add oragne juice. Spread a thin layer of chocolate over the cake, then refridgerate the cake. Repeat until all the chocolate glaze is on the cake.